apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}
  labels:
    app: {{.Release.Name}}-{{.Chart.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-{{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Chart.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}-{{.Chart.Name}}
          image: {{.Values.image.name}}:{{.Values.image.tag}}
          env:
            - name: ACTORS_HOSTNAME
              value: "actors:8082"
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /actuator/health
              port: 8088
          readinessProbe:
            httpGet:
              path: /movies/ready
              port: 8088

          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
