apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
{{- range .Values.ingress }}
  - host: {{ .host.domain }}
    http:
      paths:
      {{- range .host.paths }}
      - pathType: Prefix
        path: {{.path}}
        backend:
          service:
            name: {{ $.Release.Name}}-{{ .chart }}
            port: 
              number: {{.port}}
      {{- end }}
{{- end }}
