apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: movies-suggestion-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /movie/suggestion
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: moviesuggestion-ui
          servicePort: 8080
