apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30687
      protocol: TCP
  selector:
    app: users
    
    