apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: {{.Release.Name}}-{{.Chart.Name}}
spec:
  clusterIP: None
  ports:
    - port: 3306
  selector:
    app: {{.Release.Name}}-{{.Chart.Name}}
