apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-{{.Chart.Name}}-config
data:
  BACKEND_SERVICE_URI: {{.Values.config.BACKEND_SERVICE_URI}}
  MOVIES_SERVICE_URI: {{.Values.config.MOVIES_SERVICE_URI}}

