apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "database.fullname" .}}-pv-claim
  labels:
    app: {{ include "database.fullname" .}}-watch-list
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi