apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" .}}
  labels:
    app: {{ include "database.fullname" .}}
spec:
  clusterIP: None
  ports:
    - port: 3306
  selector:
    app: {{ include "database.fullname" .}}
