apiVersion: v1
kind: Secret
metadata:
  name: {{ include "users.fullname" .}}-auth
type: Opaque
data:
  username: {{.Values.secret.username | b64enc | quote }}
  password: {{.Values.secret.password | b64enc | quote}}
  sqlhost: {{ (include "users.database" .) | b64enc | quote}}




