apiVersion: v1
kind: Service
metadata:
  name: {{ include "users.fullname" .}}
  labels:
    app: {{ include "users.fullname" .}}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30687
      protocol: TCP
  selector:
    app: {{ include "users.fullname" .}}
    
    