apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" .}}
  labels:
    app: {{ include "frontend.fullname" .}}
spec:
  type: NodePort
  ports:
    - port: {{.Values.service.port}}
      targetPort: 3000
      nodePort: {{.Values.service.nodePort}}
      protocol: TCP
  selector:
    app: {{ include "frontend.fullname" .}}