database:
  secret:
    username: moti
    password: pass1234

frontend:
  ingress: 
    enabled: false
  config:
   BACKEND_SERVICE_URI: "http://a9bd270da439f481eb4015fb0eb6e45c-896895070.eu-west-1.elb.amazonaws.com/"
   MOVIES_SERVICE_URI: "http://a9bd270da439f481eb4015fb0eb6e45c-896895070.eu-west-1.elb.amazonaws.com/"

users:
  secret:
    username: moti
    password: pass1234
    databaseChart: database
  ingress: 
    enabled: false

movies:
  ingress: 
    enabled: false

ingress:
  - host:
      domain: a9bd270da439f481eb4015fb0eb6e45c-896895070.eu-west-1.elb.amazonaws.com
      paths:  
        - path: "/"
          chart: frontend
          port: 3000
        - path: "/movies"
          chart: movies
          port: 8088
        - path: "/auth"
          chart: users
          port: 8080
        - path: "/watchlist"
          chart: users
          port: 8080
