apiVersion: apps/v1
kind: Deployment
metadata:
  name: actors
  labels:
    app: actors
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actors
      version: v1
  template:
    metadata:
      labels:
        app: actors
        version: v1
    spec:
      containers:
        - name: actors
          image: codesparks/examples-moviesuggestion-actors:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /actuator/health
              port: 8082
          readinessProbe:
            httpGet:
              path: /actors/ready
              port: 8082