apiVersion: v1
kind: ServiceAccount
metadata:
  name: actors
  labels:
    account: actors
---
apiVersion: v1
kind: Service
metadata:
  name: actors
  labels:
    app: actors
    service: actors
spec:
  ports:
    - port: 8082
      name: http
  selector:
    app: actors

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actors
  labels:
    app: actors
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actors
      version: v1
  template:
    metadata:
      labels:
        app: actors
        version: v1
    spec:
      serviceAccountName: actors
      containers:
        - name: actors
          image: codesparks/examples-movies-watchlist-actors:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /actuator/health
              port: 8082
          readinessProbe:
            httpGet:
              path: /actors/ready
              port: 8082

