apiVersion: v1
kind: ServiceAccount
metadata:
  name: movies
  labels:
    account: movies
---
apiVersion: v1
kind: Service
metadata:
  name: movies
  labels:
    app: movies
    service: movies
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8088
      name: http
      nodePort: 30686
  selector:
    app: movies

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  labels:
    app: movies
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
      version: v1
  template:
    metadata:
      labels:
        app: movies
        version: v1
    spec:
      serviceAccountName: movies
      containers:
        - name: movies
          image: codesparks/examples-movies-watchlist-movies:1.0
          env:
            - name: ACTORS_HOSTNAME
              value: "actors:8082"
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /actuator/health
              port: 8088
          readinessProbe:
            httpGet:
              path: /movies/ready
              port: 8088

          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
