apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: "codesparks/examples-movies-watchlist-users:1.0"
          imagePullPolicy: Always
          ports:
            - name: users
              containerPort: 8080
          env:
            - name: MYSQL_DATABASE
              value: users_db
            - name: MYSQL_SERVICE_HOST
              value: mysql-service
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-auth
                  key: password         