apiVersion: v2
name: movies-watchlist
appVersion: "1.0"
description: A Helm chart for Movie Watchlist 1.0
version: 1.0.0
type: application
dependencies:
- name: frontend
  version: "1.0.0"
  repository: "http://localhost:8080"
- name: users
  version: "1.0.0"
  repository: "http://localhost:8080"
- name: movies
  version: "1.0.0"
  repository: "http://localhost:8080"
- name: database
  version: "1.0.0"
  repository: "http://localhost:8080"
