apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: movies-watch-list
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi