apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" .}}-config
data:
  BACKEND_SERVICE_URI: {{.Values.config.BACKEND_SERVICE_URI}}
  MOVIES_SERVICE_URI: {{.Values.config.MOVIES_SERVICE_URI}}

