apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" .}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "frontend.fullname" .}}
  template:
    metadata:
      labels:
        app: {{ include "frontend.fullname" .}}
    spec:
      containers:
        - name: {{ include "frontend.fullname" .}}
          image: {{.Values.image.name}}:{{.Values.image.tag}}
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 3000
          env:
            - name: BACKEND_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "frontend.fullname" .}}-config
                  key: BACKEND_SERVICE_URI
            - name: MOVIES_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "frontend.fullname" .}}-config
                  key: MOVIES_SERVICE_URI         


